name: Deploy from publish Branch

on:
  push:
    branches:
      - publish

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Build .NET project and publish
        run: |
          dotnet publish ./EmployeeApi/EmployeeApi.csproj -c Release -o ./publish

      - name: Copy publish folder to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./publish/ deployuser@192.168.20.155:/D/EmployeeApiPublish/

      - name: Run Docker Compose on server
        run: |
          ssh deployuser@192.168.20.155 "cd /D/EmployeeApiPublish && docker compose down && docker compose up -d"
