name: Deploy from deploy Branch

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted  # Your Windows Server with Docker and runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Compose - Stop Existing Services
      run: docker compose down || exit 0

    - name: Docker Compose - Build and Start
      run: docker compose up --build -d